create DATABASE IF NOT EXISTS patients_db;
USE patients_db;

DROP TABLE IF EXISTS patients;

CREATE TABLE patients(
id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
first_name VARCHAR(255) DEFAULT NULL,
last_name VARCHAR(255) DEFAULT NULL,
email VARCHAR(255) DEFAULT NULL,
phone VARCHAR(255) DEFAULT NULL,
address VARCHAR(255) DEFAULT NULL,
diagnosis VARCHAR(255) DEFAULT NULL,
image_url VARCHAR(255) DEFAULT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id),
CONSTRAINT uq_patients_email UNIQUE (email)
);


ALTER USER 'admin'@'localhost' IDENTIFIED WITH mysql_native_password BY 'none';
GRANT ALL PRIVILEGES ON *.* TO 'admin'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;
